"""
First-run setup server: web UI for entering API keys and attaching files
instead of editing .env. Used when packaging as exe.
"""
from __future__ import annotations

import json
import os
import sys
import threading
import webbrowser
from pathlib import Path
from urllib.request import urlopen, Request
from urllib.error import URLError, HTTPError

# Optional Flask import (added to requirements)
try:
    from flask import Flask, request, render_template_string
    FLASK_AVAILABLE = True
except ImportError:
    FLASK_AVAILABLE = False

# -----------------------------------------------------------------------------
# App root and config detection (works when frozen as exe or run as script)
# -----------------------------------------------------------------------------

def get_app_root() -> Path:
    """Directory where .env and config files are stored (exe dir or script dir)."""
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(__file__).resolve().parent


CONFIG_DONE_FLAG = "config_done.flag"
# SERVER_URL and API_KEY are typically embedded in the build; not required from setup form
REQUIRED_ENV_VARS = ["APIFY_API_TOKEN", "EMAIL_ADDRESS", "GEMINI_API_KEY"]


def is_config_complete() -> bool:
    """True if .env exists and required vars are set. Sentinel is written on save
    but not required here so existing users with .env are not forced to setup."""
    root = get_app_root()
    env_path = root / ".env"
    if not env_path.is_file():
        return False
    try:
        from dotenv import load_dotenv
        load_dotenv(env_path)
    except Exception:
        return False
    for var in REQUIRED_ENV_VARS:
        if not os.getenv(var) or not str(os.getenv(var)).strip():
            return False
    # Require sentinel only when we want to force first-run setup (e.g. exe).
    # If .env has all required vars, accept as complete even without flag.
    return True


def _env_value(val: str) -> str:
    """Escape and quote value for .env if needed."""
    if val is None:
        return ""
    s = str(val).strip()
    if not s:
        return ""
    if "\n" in s or "\"" in s or " " in s or "#" in s or "=" in s:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return s


def write_env_from_form(root: Path, form: dict) -> None:
    """Build .env content from form data and write to root/.env."""
    def get(name: str, default: str = "") -> str:
        return (form.get(name) or "").strip() or default

    lines = [
        "# Generated by setup page - do not edit manually",
        "USE_LOCAL_STORAGE=" + ("true" if get("use_local_storage") == "on" else "false"),
        "EMAIL_ADDRESS=" + _env_value(get("email_address")),
        "CRAWL_LINKEDIN=" + ("true" if get("crawl_linkedin") == "on" else "false"),
        "LINKEDIN_PASSWORD=" + _env_value(get("linkedin_password")),
        "APIFY_API_TOKEN=" + _env_value(get("apify_api_token")),
        # "SERVER_URL=" + _env_value(get("server_url")),  # embedded in build
        # "API_KEY=" + _env_value(get("api_key")),  # embedded in build
        "GEMINI_API_KEY=" + _env_value(get("gemini_api_key")),
        "BACKUP_GEMINI_API_KEY=" + _env_value(get("backup_gemini_api_key")),
        "GEMINI_MODEL=" + _env_value(get("gemini_model") or "gemini-2.0-flash"),
        "CHECK_SUSTAINABILITY=" + ("true" if get("check_sustainability") == "on" else "false"),
    ]
    resume_path = get("resume_path", "").strip()
    if resume_path:
        lines.append("RESUME_PDF_PATH=" + _env_value(resume_path))
    env_path = root / ".env"
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# -----------------------------------------------------------------------------
# Validation helpers (Apify, Gemini, Server URL)
# -----------------------------------------------------------------------------

def validate_apify_token(token: str) -> tuple[bool, str]:
    """Check Apify token with a minimal request."""
    if not token or not token.strip():
        return False, "Token is empty"
    try:
        from apify_client import ApifyClient
        client = ApifyClient(token.strip())
        # List actors or user info to verify token
        client.http_client.get("https://api.apify.com/v2/users/me")
        return True, "OK"
    except Exception as e:
        return False, str(e)


def validate_gemini_key(key: str) -> tuple[bool, str]:
    """Check Gemini API key with a minimal request."""
    if not key or not key.strip():
        return False, "Key is empty"
    try:
        import google.genai as genai
        from google.genai import types
        client = genai.Client(api_key=key.strip())
        client.models.generate_content(
            model="gemini-2.0-flash",
            contents="Say OK in one word.",
            config=types.GenerateContentConfig(max_output_tokens=10),
        )
        return True, "OK"
    except Exception as e:
        return False, str(e)


def validate_server_url(url: str, api_key: str) -> tuple[bool, str]:
    """Check API server reachability."""
    if not url or not url.strip():
        return False, "URL is empty"
    u = url.strip().rstrip("/")
    try:
        req = Request(u, headers={"Authorization": f"Bearer {api_key}"} if api_key else {})
        resp = urlopen(req, timeout=10)
        return True, f"OK (status {resp.getcode()})"
    except HTTPError as he:
        return False, f"HTTP {he.code}"
    except URLError as ue:
        return False, str(ue.reason) if getattr(ue, "reason", None) else str(ue)
    except Exception as e:
        return False, str(e)


# -----------------------------------------------------------------------------
# HTML template (single string for exe packaging)
# -----------------------------------------------------------------------------

SETUP_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Job Application Preprocessor – Setup</title>
  <style>
    :root { --bg: #1a1c24; --card: #21262d; --border: #3d444d; --text: #e6edf3; --muted: #8b949e; --accent: #58a6ff; --err: #f85149; --ok: #3fb950; }
    * { box-sizing: border-box; }
    body { font-family: system-ui, -apple-system, sans-serif; background: var(--bg); color: var(--text); margin: 0; padding: 20px; line-height: 1.5; }
    .container { max-width: 640px; margin: 0 auto; }
    h1 { font-size: 1.5rem; margin-bottom: 8px; }
    .subtitle { color: var(--muted); margin-bottom: 24px; }
    section { background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 20px; margin-bottom: 20px; }
    section h2 { font-size: 1.1rem; margin: 0 0 16px 0; color: var(--text); }
    label { display: block; margin-bottom: 4px; color: var(--muted); font-size: 0.9rem; }
    label .required { color: var(--err); }
    input[type="text"], input[type="password"], input[type="url"], input[type="file"], textarea { width: 100%; padding: 10px 12px; margin-bottom: 12px; border: 1px solid var(--border); border-radius: 8px; background: var(--bg); color: var(--text); }
    textarea { min-height: 80px; resize: vertical; }
    input[type="checkbox"] { margin-right: 8px; vertical-align: middle; }
    .hint { font-size: 0.85rem; color: var(--muted); margin-top: -8px; margin-bottom: 12px; }
    a { color: var(--accent); }
    .links { margin: 12px 0; }
    .links a { margin-right: 12px; }
    .msg { padding: 12px; border-radius: 8px; margin-bottom: 16px; }
    .msg.error { background: rgba(248,81,73,0.15); border: 1px solid var(--err); color: var(--err); }
    .msg.success { background: rgba(63,185,80,0.15); border: 1px solid var(--ok); color: var(--ok); }
    .validate-result { margin-top: 8px; font-size: 0.9rem; }
    .validate-result.ok { color: var(--ok); }
    .validate-result.err { color: var(--err); }
    button { padding: 10px 20px; border-radius: 8px; border: 1px solid var(--border); background: var(--card); color: var(--text); cursor: pointer; font-size: 1rem; }
    button.primary { background: var(--accent); color: #fff; border-color: var(--accent); }
    button + button { margin-left: 8px; }
    .advanced { margin-top: 16px; }
    .advanced summary { cursor: pointer; color: var(--muted); }
  </style>
</head>
<body>
  <div class="container">
    <h1>Job Application Preprocessor – Setup</h1>
    <p class="subtitle">Enter your API keys and optional files. All values stay on your computer.</p>

    <section>
      <h2>Apify (LinkedIn job data)</h2>
      <p class="hint">Apify provides <strong>$5 in free platform credits every month</strong>. This app uses it for LinkedIn job listings, job details, and company overviews (actors: linkedin-jobs-scraper-api, linkedin-job-detail, linkedin-company-detail). With $5 you can typically process on the order of <strong>thousands of job listings</strong> and <strong>hundreds of company/job-detail enrichments</strong> per month. Exact limits: <a href="#placeholder-apify-pricing" id="link-apify-pricing">Apify pricing (link to be added)</a>. Check your usage in the Apify console so you’re not surprised when the app pauses Apify after the monthly cap.</p>
      <div class="links">
        <a href="https://console.apify.com/sign-up" target="_blank" rel="noopener">Create Apify account</a>
        <a href="https://console.apify.com/settings/integrations" target="_blank" rel="noopener">Create Apify API key</a>
      </div>
      <label for="apify_api_token">Apify API token <span class="required">*</span></label>
      <input type="password" id="apify_api_token" name="apify_api_token" placeholder="apify_api_..." autocomplete="off">
    </section>

    <section>
      <h2>Google Gemini</h2>
      <div class="links">
        <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noopener">Get Gemini API key</a>
      </div>
      <label for="gemini_api_key">Gemini API key <span class="required">*</span></label>
      <input type="password" id="gemini_api_key" name="gemini_api_key" placeholder="AIza..." autocomplete="off">
      <details class="advanced">
        <summary>Advanced</summary>
        <label for="backup_gemini_api_key">Backup Gemini API key (optional)</label>
        <input type="password" id="backup_gemini_api_key" name="backup_gemini_api_key" autocomplete="off">
        <label for="gemini_model">Gemini model</label>
        <input type="text" id="gemini_model" name="gemini_model" value="gemini-2.0-flash" placeholder="gemini-2.0-flash">
      </details>
    </section>

    <!-- SERVER_URL and API_KEY are embedded in the build; not shown in setup form -->
    <section>
      <h2>Your contact & location</h2>
      <label for="email_address">Email address (used by the app) <span class="required">*</span></label>
      <input type="text" id="email_address" name="email_address" placeholder="you@example.com" autocomplete="email">
      <label for="location">Default job search location (e.g. Remote, London, United States)</label>
      <input type="text" id="location" name="location" placeholder="e.g. Remote" autocomplete="off">
      <p class="hint">Used when generating LinkedIn search parameters if not specified in additional details.</p>
    </section>

    <section>
      <h2>Optional</h2>
      <label><input type="checkbox" name="use_local_storage" checked> Use local storage (recommended)</label>
      <label><input type="checkbox" name="check_sustainability"> Check company sustainability</label>
      <p class="hint">If you prioritize financial stability or maximum job options, leave this off — sustainability filtering can reduce matches.</p>
      <label><input type="checkbox" name="crawl_linkedin"> Enable LinkedIn crawling</label>
      <div id="linkedin_password_row" style="display:none;">
        <label for="linkedin_password">LinkedIn password</label>
        <input type="password" id="linkedin_password" name="linkedin_password" autocomplete="off">
      </div>
    </section>

    <section>
      <h2>Files</h2>
      <label for="resume_pdf">Resume (PDF)</label>
      <input type="file" id="resume_pdf" name="resume_pdf" accept=".pdf">
      <label for="additional_details">Additional details (text)</label>
      <textarea id="additional_details" name="additional_details" placeholder="Career goals, salary expectations, location preferences..."></textarea>
      <p class="hint">Use the button below to generate a structured resume (resume_data.json) from this text. Include your full name, experience, and skills for best results.</p>
      <p>
        <button type="button" id="btn_generate_resume_from_text">Generate resume from text</button>
        <span class="hint" style="margin-left: 0.5em;">⚠️ This will overwrite resume_data.json if it already exists.</span>
      </p>
      <label for="job_preferences_file">Job preferences (YAML, optional)</label>
      <input type="file" id="job_preferences_file" name="job_preferences_file" accept=".yaml,.yml">
    </section>

    <div id="message"></div>
    <div id="validate_results"></div>
    <button type="button" id="btn_validate">Validate</button>
    <button type="button" id="btn_save" class="primary">Save configuration</button>

    <form id="save_form" method="post" action="/save" enctype="multipart/form-data" style="display:none;">
      <input type="hidden" id="f_apify_api_token" name="apify_api_token">
      <input type="hidden" id="f_gemini_api_key" name="gemini_api_key">
      <input type="hidden" id="f_backup_gemini_api_key" name="backup_gemini_api_key">
      <input type="hidden" id="f_gemini_model" name="gemini_model">
      <input type="hidden" id="f_email_address" name="email_address">
      <input type="hidden" id="f_location" name="location">
      <input type="hidden" id="f_linkedin_password" name="linkedin_password">
      <input type="hidden" id="f_use_local_storage" name="use_local_storage">
      <input type="hidden" id="f_check_sustainability" name="check_sustainability">
      <input type="hidden" id="f_crawl_linkedin" name="crawl_linkedin">
      <input type="hidden" id="f_additional_details" name="additional_details">
      <input type="hidden" id="f_resume_path" name="resume_path">
    </form>
  </div>
  <script>
    document.querySelector('input[name="crawl_linkedin"]').addEventListener('change', function() {
      document.getElementById('linkedin_password_row').style.display = this.checked ? 'block' : 'none';
    });
    function showMessage(text, isError) {
      var el = document.getElementById('message');
      el.innerHTML = '<div class="msg ' + (isError ? 'error' : 'success') + '">' + text + '</div>';
    }
    function showValidateResults(results) {
      var html = '';
      ['apify', 'gemini'].forEach(function(k) {
        var r = results[k];
        if (!r) return;
        html += '<div class="validate-result ' + (r.ok ? 'ok' : 'err') + '">' + k + ': ' + (r.ok ? 'OK' : r.message) + '</div>';
      });
      document.getElementById('validate_results').innerHTML = html;
    }
    document.getElementById('btn_generate_resume_from_text').addEventListener('click', function() {
      var text = document.getElementById('additional_details').value.trim();
      if (!text || text.length < 20) {
        showMessage('Please enter at least a few sentences in Additional details (include your name, experience, skills).', true);
        return;
      }
      var btn = document.getElementById('btn_generate_resume_from_text');
      btn.disabled = true;
      btn.textContent = 'Generating...';
      fetch('/generate-resume-from-text', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: text })
      }).then(function(res) { return res.json(); }).then(function(data) {
        btn.disabled = false;
        btn.textContent = 'Generate resume from text';
        if (data.error) { showMessage(data.error, true); return; }
        showMessage('Resume generated and saved as resume_data.json.', false);
      }).catch(function(e) {
        btn.disabled = false;
        btn.textContent = 'Generate resume from text';
        showMessage('Request failed: ' + e.message, true);
      });
    });
    document.getElementById('btn_validate').addEventListener('click', function() {
      var results = document.getElementById('validate_results');
      results.innerHTML = 'Validating...';
      fetch('/validate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          apify_api_token: document.getElementById('apify_api_token').value,
          gemini_api_key: document.getElementById('gemini_api_key').value
        })
      }).then(function(res) { return res.json(); }).then(function(data) {
        showValidateResults(data);
      }).catch(function(e) {
        results.innerHTML = '<div class="validate-result err">Request failed: ' + e.message + '</div>';
      });
    });
    document.getElementById('btn_save').addEventListener('click', function() {
      var apify = document.getElementById('apify_api_token').value.trim();
      var gemini = document.getElementById('gemini_api_key').value.trim();
      var email = document.getElementById('email_address').value.trim();
      if (!apify || !gemini || !email) {
        showMessage('Please fill all required fields (Apify token, Gemini key, Email).', true);
        return;
      }
      document.getElementById('f_apify_api_token').value = apify;
      document.getElementById('f_gemini_api_key').value = gemini;
      document.getElementById('f_backup_gemini_api_key').value = document.getElementById('backup_gemini_api_key').value;
      document.getElementById('f_gemini_model').value = document.getElementById('gemini_model').value || 'gemini-2.0-flash';
      document.getElementById('f_email_address').value = email;
      document.getElementById('f_location').value = document.getElementById('location').value || '';
      document.getElementById('f_linkedin_password').value = document.getElementById('linkedin_password').value;
      document.getElementById('f_use_local_storage').value = document.querySelector('input[name="use_local_storage"]').checked ? 'on' : '';
      document.getElementById('f_check_sustainability').value = document.querySelector('input[name="check_sustainability"]').checked ? 'on' : '';
      document.getElementById('f_crawl_linkedin').value = document.querySelector('input[name="crawl_linkedin"]').checked ? 'on' : '';
      document.getElementById('f_additional_details').value = document.getElementById('additional_details').value;
      document.getElementById('f_resume_path').value = ''; // Set by server after upload
      var form = document.getElementById('save_form');
      var fd = new FormData();
      fd.append('apify_api_token', apify);
      fd.append('gemini_api_key', gemini);
      fd.append('backup_gemini_api_key', document.getElementById('backup_gemini_api_key').value);
      fd.append('gemini_model', document.getElementById('gemini_model').value || 'gemini-2.0-flash');
      fd.append('email_address', email);
      fd.append('location', document.getElementById('location').value || '');
      fd.append('linkedin_password', document.getElementById('linkedin_password').value);
      fd.append('use_local_storage', document.querySelector('input[name="use_local_storage"]').checked ? 'on' : '');
      fd.append('check_sustainability', document.querySelector('input[name="check_sustainability"]').checked ? 'on' : '');
      fd.append('crawl_linkedin', document.querySelector('input[name="crawl_linkedin"]').checked ? 'on' : '');
      fd.append('additional_details', document.getElementById('additional_details').value);
      var resumeFile = document.getElementById('resume_pdf').files[0];
      if (resumeFile) fd.append('resume_pdf', resumeFile);
      var prefFile = document.getElementById('job_preferences_file').files[0];
      if (prefFile) fd.append('job_preferences_file', prefFile);
      fetch('/save', { method: 'POST', body: fd }).then(function(res) { return res.json(); }).then(function(data) {
        if (data.error) { showMessage(data.error, true); return; }
        showMessage('Configuration saved. Close this tab, then stop the app (Ctrl+C in the terminal if it is still running) and run it again to start the main application.', false);
      }).catch(function(e) {
        showMessage('Save failed: ' + e.message, true);
      });
    });
  </script>
</body>
</html>
"""


# -----------------------------------------------------------------------------
# Flask app and routes
# -----------------------------------------------------------------------------

def create_app(app_root: Path):
    app = Flask(__name__)
    app.config["APP_ROOT"] = app_root
    app.config["MAX_CONTENT_LENGTH"] = 32 * 1024 * 1024  # 32 MB for resume PDF

    @app.route("/")
    def index():
        return render_template_string(SETUP_HTML)

    @app.route("/validate", methods=["POST"])
    def validate():
        data = request.get_json() or {}
        result = {}
        token = (data.get("apify_api_token") or "").strip()
        ok, msg = validate_apify_token(token)
        result["apify"] = {"ok": ok, "message": msg}
        key = (data.get("gemini_api_key") or "").strip()
        ok, msg = validate_gemini_key(key)
        result["gemini"] = {"ok": ok, "message": msg}
        # SERVER_URL and API_KEY are embedded in build; skip server validation
        return result

    @app.route("/save", methods=["POST"])
    def save():
        root = app.config["APP_ROOT"]
        form = request.form.to_dict()
        # Handle resume PDF upload
        resume_path_val = ""
        if "resume_pdf" in request.files:
            f = request.files["resume_pdf"]
            if f and f.filename and f.filename.lower().endswith(".pdf"):
                path = root / "resume.pdf"
                f.save(str(path))
                resume_path_val = str(path)
        form["resume_path"] = resume_path_val
        # Handle additional_details (from form field)
        if "additional_details" not in form:
            form["additional_details"] = ""
        # Handle job_preferences file
        if "job_preferences_file" in request.files:
            pf = request.files["job_preferences_file"]
            if pf and pf.filename:
                path = root / "job_preferences.yaml"
                pf.save(str(path))
        # If location was set in the form, update job_preferences.yaml (create or merge)
        location_val = (form.get("location") or "").strip()
        if location_val:
            import os
            from config import _get_job_filters, _save_job_filters
            orig_cwd = os.getcwd()
            try:
                os.chdir(root)
                filters = _get_job_filters()
                filters["default_search_location"] = location_val
                _save_job_filters(filters)
            finally:
                os.chdir(orig_cwd)
        add_path = root / "additional_details.txt"
        add_text = (form.get("additional_details") or "").strip()
        if add_text:
            add_path.write_text(add_text, encoding="utf-8")
        try:
            write_env_from_form(root, form)
        except Exception as e:
            return {"error": f"Failed to write .env: {e}"}, 400
        (root / CONFIG_DONE_FLAG).write_text("", encoding="utf-8")
        return {"ok": True}

    @app.route("/generate-resume-from-text", methods=["POST"])
    def generate_resume_from_text():
        root = app.config["APP_ROOT"]
        try:
            from dotenv import load_dotenv
            load_dotenv(root / ".env")
        except Exception:
            pass
        data = request.get_json() or {}
        text = (data.get("text") or "").strip()
        if len(text) < 20:
            return {"error": "Provide at least a few sentences (include your name, experience, skills)."}, 400
        try:
            from api_methods import create_resume_json_from_text
            out_path = str(root / "resume_data.json")
            create_resume_json_from_text(text, output_path=out_path)
            return {"ok": True}
        except Exception as e:
            return {"error": str(e)}, 400

    return app


def run_setup_server(port: int = 0) -> bool:
    """
    Start the setup Flask server, open browser, block until config is saved (or server stops).
    Returns True if config was saved (caller should continue into main app).
    """
    if not FLASK_AVAILABLE:
        print("Flask is required for the setup page. Install with: pip install flask")
        return False
    root = get_app_root()
    app = create_app(root)
    # Find an available port if port=0
    import socket
    if port == 0:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.bind(("127.0.0.1", 0))
            port = s.getsockname()[1]
    url = f"http://127.0.0.1:{port}"
    print(f"Opening setup page at {url}")
    threading.Thread(target=lambda: webbrowser.open(url), daemon=True).start()
    try:
        app.run(host="127.0.0.1", port=port, threaded=True, use_reloader=False)
    except Exception as e:
        print(f"Setup server stopped: {e}")
    return is_config_complete()


def run_setup_if_needed() -> bool:
    """
    If config is not complete, run the setup server and block until user saves.
    Returns True if we can proceed (config is complete); False to exit.
    """
    if is_config_complete():
        return True
    print("Configuration missing or incomplete. Opening setup page in your browser...")
    if run_setup_server(port=5867):
        return True
    return is_config_complete()
